// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TYGunQjXqpHymzSZizMRcP9EeAPt_JI',
    appId: '1:232697583897:android:9b061d57864b6825610d88',
    messagingSenderId: '232697583897',
    projectId: 'shimarin-chill',
    databaseURL: 'https://shimarin-chill-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shimarin-chill.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOs_OWsgdLUFUb3ycmO0NZek9NNpoxeso',
    appId: '1:232697583897:ios:14260a83d90a1625610d88',
    messagingSenderId: '232697583897',
    projectId: 'shimarin-chill',
    databaseURL: 'https://shimarin-chill-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shimarin-chill.firebasestorage.app',
    iosBundleId: 'com.example.shimarinChill',
  );
}
